#!/bin/sh
set -eu

if [ $# -lt 1 ]; then
    aria2c -h
    exit 1
fi

self=$(readlink -f "$0")
here=$(dirname "$self")

np=$(nproc)
lnp=$((np * 2))
wnp=$((np * 3))

# shellcheck disable=SC2046
aria2c -c -V -k1M -s$lnp -x16 -j$wnp --max-tries=3 --retry-wait=5 $(sed -r "s|\s+|/$1 |g" "$here/proxy.conf")
