#!/bin/sh
set -eu
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

cache="$here/proxy.conf"

case "${1:-update}" in
    update)
        node "$here/main.js" 2> /dev/null | tee "$cache"
        ;;
    list)
        [ -f "$here/proxy.conf" ] && cat "$cache" || node "$here/main.js" 2> /dev/null | tee "$cache"
        ;;
    *) ;;
esac
